trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build React app'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'my-app-service-connection' # Service connection name
    appName: 'my-react-app' # Your Azure App Service name
    package: '$(System.DefaultWorkingDirectory)/build'
    runtimeStack: 'NODE|22-lts'
